name: Python CI with Appium

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest  # macOS 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 파이썬 버전 설정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 필요한 패키지 설치

      - name: Set up Android SDK
        run: |
          echo "Setting up Android SDK..."
          # Android Command Line Tools 다운로드
          curl -L https://dl.google.com/android/repository/commandlinetools-mac-8512546_latest.zip -o /tmp/cmdline-tools.zip
          # 압축 해제
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          unzip /tmp/cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools
          # 환경 변수 설정
          echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          # sdkmanager 실행 가능하도록 환경 변수 반영
          source $GITHUB_ENV
          # sdkmanager 사용 가능 확인
          sdkmanager --version
          # sdkmanager 라이센스 동의
          sdkmanager --licenses
          sdkmanager "system-images;android-29;google_apis;x86_64"

      - name: Set up Android Emulator
        run: |
          echo "Setting up AVD..."
          avdmanager create avd -n testAVD -k "system-images;android-29;google_apis;x86_64"
          emulator -avd testAVD -no-window -no-audio -gpu off &  # 에뮬레이터 실행

      - name: Run Appium tests
        run: |
          appium &  # Appium 서버 실행
          python -m unittest discover tests  # 테스트 실행
