name: Appium Automation

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Android SDK
      run: |
        # Android SDK 경로 생성
        mkdir -p $HOME/Android/Sdk
        
        # SDK 도구 설치
        echo "Setting up Android SDK..."
        echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/tools" >> $GITHUB_ENV
        
        # SDK 업데이트 및 필요한 패키지 설치
        sdkmanager --update
        sdkmanager "platform-tools" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64"
        sdkmanager --list

    - name: Set up AVD (Android Virtual Device)
      run: |
        # AVD 생성
        echo "Creating AVD..."
        echo "no" | avdmanager create avd -n testAVD -k "system-images;android-30;google_apis;x86_64"
        
        # AVD 시작
        echo "Starting AVD..."
        nohup $ANDROID_HOME/emulator/emulator -avd testAVD -no-window &

        # AVD 초기화 기다리기
        sleep 60

    - name: Install Appium and dependencies
      run: |
        # Node.js와 Appium 설치
        npm install -g appium
        appium --version

    - name: Run Appium tests
      run: |
        # Appium 테스트 실행
        appium --use-plugins element-wait
        # 추가 테스트 실행 명령어들
        python -m unittest discover -s tests

    - name: Clean up AVD
      run: |
        # AVD 종료
        adb -s emulator-5554 emu kill