name: Run Appium & API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # pytest 및 의존성 설치

    - name: Install Appium
      run: |
        npm install -g appium  # Appium 전역 설치

    - name: Install Appium UiAutomator2 driver
      run: |
        appium driver install uiautomator2  # UiAutomator2 드라이버 설치

    - name: Install adb (Android Debug Bridge)
      run: |
        sudo apt-get update
        sudo apt-get install android-tools-adb  # adb 설치

    - name: Start Appium server
      run: |
        nohup appium > appium.log 2>&1 &  # Appium 서버 실행, 로그를 appium.log에 저장
        sleep 10  # Appium 서버 시작 후 10초 대기

    - name: Check Appium server status
      run: |
        # Appium 서버 로그가 appium.log에 있는지 확인
        tail -n 20 appium.log  # 최근 20줄 로그 출력
        # Appium 서버가 정상적으로 실행되었는지 확인
        if ! grep -q "Appium REST http interface listener started" appium.log; then
          echo "Appium server did not start correctly. Exiting."
          exit 1
        fi
        echo "Appium server started successfully."

    - name: Verify connected Android devices
      run: |
        adb devices  # 연결된 Android 디바이스 확인

    - name: Run tests
      run: |
        pytest test_Appium_API2.py  # Appium API 테스트 실행

    - name: Run flake8 linting
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # flake8 실행