name: Appium Android Test on Physical Device

on:
  push:
    branches:
      - main

jobs:
  android-test:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt update
        sudo apt install -y android-sdk
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Set up Appium
      run: |
        npm install -g appium

    - name: Start Appium server
      run: |
        appium &

    - name: Set up adb
      run: |
        adb start-server

    - name: Wait for device to be recognized
      run: |
        adb devices
        sleep 10
        adb devices  # 재차 확인

    - name: Run Appium tests
      run: |
        # Appium을 통해 테스트 실행
        python -m unittest test_Appium_API2.py
