name: Run Appium Tests on Physical Device

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt update
        sudo apt install -y android-sdk
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Install Appium
      run: |
        npm install -g appium

    - name: Start Appium server
      run: |
        appium &

    - name: Wait for device to be recognized
      run: |
        adb start-server
        sleep 10
        adb devices  # 디바이스가 정상적으로 연결되었는지 확인

    - name: Run Appium tests
      run: |
        python -m unittest test_Appium_API2.py  # 실제 테스트 파일 실행
