name: Python CI with Appium

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest  # macOS 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 파이썬 버전 설정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 필요한 패키지 설치

      - name: Set up Android Emulator
        run: |
          echo "Setting up AVD..."
          sdkmanager "system-images;android-29;google_apis;x86_64"
          avdmanager create avd -n testAVD -k "system-images;android-29;google_apis;x86_64"
          emulator -avd testAVD -no-window -no-audio -gpu off &  # 에뮬레이터 실행

      - name: Run Appium tests
        run: |
          appium &  # Appium 서버 실행
          python -m unittest discover tests  # 테스트 실행
