name: Appium Automation

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Android SDK
      run: |
        # Android SDK 경로 생성
        mkdir -p $HOME/Android/Sdk
        
        # SDK cmdline-tools 다운로드
        echo "Downloading Android SDK cmdline-tools..."
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-mac-8512546_latest.zip
        
        # SDK 도구 압축 해제
        unzip sdk-tools.zip -d $HOME/Android/Sdk/cmdline-tools
        
        # 최신 버전 경로 설정
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
        
        # 환경 변수 설정
        echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/tools" >> $GITHUB_ENV
        
        # 환경 변수 반영
        source $GITHUB_ENV
        
        # SDK 업데이트 및 필요한 패키지 설치
        echo "Updating SDK tools..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
        
        # 시스템 이미지 설치 (경로 확인 후 사용)
        echo "Installing system image for AVD..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-30;google_apis;x86_64"

    - name: Set up AVD (Android Virtual Device)
      run: |
        # AVD 생성
        echo "Creating AVD..."
        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n testAVD -k "system-images;android-30;google_apis;x86_64"
        
        # AVD 시작
        echo "Starting AVD..."
        nohup $ANDROID_HOME/emulator/emulator -avd testAVD -no-window &
        
        # AVD 초기화 기다리기
        sleep 60

    - name: Install Appium and dependencies
      run: |
        # Node.js와 Appium 설치
        npm install -g appium
        appium --version

    - name: Run Appium tests
      run: |
        # Appium 테스트 실행
        appium --use-plugins element-wait
        # 추가 테스트 실행 명령어들
        python -m unittest discover -s tests

    - name: Clean up AVD
      run: |
        # AVD 종료
        adb -s emulator-5554 emu kill